version: '2'
services:
  customerportal-app:
    image: customerportal
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:postgresql://customerportal-postgresql:5432/CustomerPortal
      - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
    ports:
      - 8081:8081
  customerportal-postgresql:
    extends:
      file: postgresql.yml
      service: customerportal-postgresql
